#!/bin/bash

## Solution for managing a Windows Terminal configuration in git that can be used in different user accounts ##
WT_TARGET_FILE="$LOCALAPPDATA/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
WT_CURRENT_FILE="Windows_Terminal/settings-current.json"
WT_TEMPLATE_FILE="Windows_Terminal/settings-template.json"
WT_TARGET_DIR=$(dirname "$WT_TARGET_FILE")

# Get the current Windows Terminal configuration state and process it
if [[ -f $WT_TARGET_FILE ]]; then
  sed 's/^ *\/\/.*//' "$WT_TARGET_FILE" | \
    jq -r 'to_entries | sort_by(.key) | from_entries | .actions |= sort_by(.command)' > "$WT_CURRENT_FILE"
fi

# Check if pwsh (PowerShell Core) is available in PATH
if command -v pwsh &> /dev/null
then
    core=false
    powershell=true
else
    core=true
    powershell=false
fi

# Check which WSL distros are installed
bool() {
  if wsl.exe -l | tr -d '\0' | grep -iq "$1"; then echo "false"; else echo "true"; fi
}

# Replace the placeholders in the template and write to target
if [[ ! -d $WT_TARGET_DIR ]]; then mkdir -p "$WT_TARGET_DIR"; fi
sed -e "s/{{DEFAULT_WSL}}/$DEFAULT_WSL/" \
  -e "s/{{PENGWIN}}/$(bool "WLinux")/" \
  -e "s/{{UBUNTU}}/$(bool "Ubuntu")/" \
  -e "s/{{FEDORA}}/$(bool "fedoraremix")/" \
  -e "s/{{ORACLE}}/$(bool "Oracle")/" \
  -e "s/{{NIXOS}}/$(bool "NixOS")/" \
  -e "s/{{KALI}}/$(bool "kali-linux")/" \
  -e "s/{{POWERSHELL}}/$powershell/" \
  -e "s/{{POWERSHELLCORE}}/$core/" \
  -e "s/{{PYTHON_PATH}}/$(where.exe python.exe | head -n 1 | sed 's/\\/\\\\\\\\/g')/" \
  "$WT_TEMPLATE_FILE" > "$WT_TARGET_FILE"

## Other stuff ##
find . -name 'desktop.ini' -exec attrib.exe +A +S +H {} \;
find . -name '.*?' -not -path './Settings/*' -exec attrib.exe +H {} \;
