# Windows 11 Enterprise
Vagrant.configure("2") do |config|
  config.vm.define "win11", primary: true do |win11|
    win11.vm.box = "gusztavvargadr/windows-11"
    win11.vm.box_version = "2302.0.2409"
    win11.vm.hostname = "Win11"
    win11.vm.boot_timeout = 600

    # Detect keyboard layout and time zone from host (presently only works for Windows hosts)
    language = `powershell -Command "Get-WinUserLanguageList | Select-Object -ExpandProperty LanguageTag"`.strip
    time_zone = `powershell -Command "tzutil /g"`.strip

    # Pass time_zone and language as arguments
    win11.vm.provision "shell", path: "scripts/regional_settings.ps1", args: [time_zone, language], privileged: true
    # Fix winget
    win11.vm.provision "shell", path: "scripts/fix_winget.ps1", privileged: true
  end

  # Provider-specific configurations
  config.vm.provider "hyperv" do |hv|
    hv.vmname = "Win11_bootstrap_test"
    hv.memory = "4096"
    hv.cpus = 2
    hv.enable_virtualization_extensions = true
    hv.linked_clone = true
  end

  config.vm.provider "virtualbox" do |vb|
    vb.vmname = "Win11_bootstrap_test"
    vb.memory = "4096"
    vb.cpus = 2
    vb.gui = true
  end
end
